// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDDxMogADKc06jk9t8_9JPUalP-K9CxwQU',
//     appId: '1:923380302932:web:8cca42f0f609b3474859c1',
//     messagingSenderId: '923380302932',
//     projectId: 'geoat-2f636',
//     authDomain: 'geoat-2f636.firebaseapp.com',
//     storageBucket: 'geoat-2f636.appspot.com',
//     measurementId: 'G-D4R2PHHP72',
//   );

//   static FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCA99NnDP446z_q3rpt4L9VRqMqkrz--E4',
//     appId: '1:923380302932:android:b08d64252a772d784859c1',
//     messagingSenderId: '923380302932',
//     projectId: 'geoat-2f636',
//     storageBucket: 'geoat-2f636.appspot.com',
//   );

//   static FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBgmdVnzD_zZ1NH04PtxN3jEZhih58MzkA',
//     appId: '1:923380302932:ios:c4e3ef89d4425e3a4859c1',
//     messagingSenderId: '923380302932',
//     projectId: 'geoat-2f636',
//     storageBucket: 'geoat-2f636.appspot.com',
//     iosBundleId: 'com.example.app',
//   );

//   static FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBgmdVnzD_zZ1NH04PtxN3jEZhih58MzkA',
//     appId: '1:923380302932:ios:c4e3ef89d4425e3a4859c1',
//     messagingSenderId: '923380302932',
//     projectId: 'geoat-2f636',
//     storageBucket: 'geoat-2f636.appspot.com',
//     iosBundleId: 'com.example.app',
//   );

//   static FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDDxMogADKc06jk9t8_9JPUalP-K9CxwQU',
//     appId: '1:923380302932:web:ce3fc79def8002d24859c1',
//     messagingSenderId: '923380302932',
//     projectId: 'geoat-2f636',
//     authDomain: 'geoat-2f636.firebaseapp.com',
//     storageBucket: 'geoat-2f636.appspot.com',
//     measurementId: 'G-LG2YSCJTCM',
//   );
// }
